(() => {
  "use strict";
  const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  function initMenu(){const b=$(".menu-button"),n=$(".main-nav");if(!b||!n)return;const close=()=>{n.classList.remove("open");b.setAttribute("aria-expanded","false");b.setAttribute("aria-label","메뉴 열기");document.body.classList.remove("nav-open")};const open=()=>{n.classList.add("open");b.setAttribute("aria-expanded","true");b.setAttribute("aria-label","메뉴 닫기");document.body.classList.add("nav-open")};b.addEventListener("click",()=>n.classList.contains("open")?close():open());$$("a",n).forEach(a=>a.addEventListener("click",close));document.addEventListener("keydown",e=>{if(e.key==="Escape")close()});document.addEventListener("click",e=>{if(n.classList.contains("open")&&!n.contains(e.target)&&!b.contains(e.target))close()});window.addEventListener("resize",()=>{if(innerWidth>900)close()},{passive:true})}
  function initImageSliders(){$$("[data-slider]").forEach(slider=>{const slides=$$(":scope > img",slider);if(slides.length<2)return;let i=Math.max(0,slides.findIndex(s=>s.classList.contains("is-active")));const delay=Math.max(2500,Number(slider.dataset.interval)||4000),hero=slider.classList.contains("hero-slides"),current=hero?$(".hero-progress b"):null,total=hero?$(".hero-progress em"):null,bar=hero?$(".hero-progress i"):null;const show=n=>{i=(n+slides.length)%slides.length;slides.forEach((s,x)=>s.classList.toggle("is-active",x===i));if(current)current.textContent=String(i+1).padStart(2,"0");if(total)total.textContent=String(slides.length).padStart(2,"0");if(bar){bar.style.width=`${100/slides.length}%`;bar.style.transform=`translateX(${i*100}%)`;bar.style.transformOrigin="left"}};show(i);if(!reduced)setInterval(()=>show(i+1),delay)})}
  function initReveal(){const items=$$(".reveal");if(!items.length)return;if(reduced||!("IntersectionObserver" in window)){items.forEach(x=>x.classList.add("visible"));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");io.unobserve(e.target)}}),{threshold:.12});items.forEach(x=>io.observe(x))}
  function initVideoGuides(){$$("iframe").forEach(f=>{if(f.src.includes("VIDEO_ID"))return;const g=f.nextElementSibling;if(g&&(g.classList.contains("short-guide")||g.classList.contains("video-guide")))g.remove()})}
  function carousel(root,sel,delay=5200){const slides=$$(sel.slide,root);if(!slides.length)return null;const dots=$$(sel.dot,root),prev=$(sel.prev,root),next=$(sel.next,root);let i=0,t=null;const show=n=>{i=(n+slides.length)%slides.length;slides.forEach((s,x)=>s.classList.toggle("is-active",x===i));dots.forEach((d,x)=>{const a=x===i;d.classList.toggle("is-active",a);d.setAttribute("aria-current",a?"true":"false")})},stop=()=>{if(t)clearInterval(t);t=null},start=()=>{stop();if(!reduced&&slides.length>1&&!document.hidden)t=setInterval(()=>show(i+1),delay)};prev?.addEventListener("click",()=>{show(i-1);start()});next?.addEventListener("click",()=>{show(i+1);start()});dots.forEach((d,x)=>d.addEventListener("click",()=>{show(x);start()}));root.addEventListener("mouseenter",stop);root.addEventListener("mouseleave",start);root.addEventListener("focusin",stop);root.addEventListener("focusout",start);show(0);start();return{show,start,stop}}
  function initTour(){$$(".tour-slider").forEach(s=>carousel(s,{slide:".tour-slide",dot:".tour-dot",prev:".tour-prev",next:".tour-next"},Math.max(2500,Number(s.dataset.autoplay)||5200)))}
  function initRooms(){const data=window.ROOM_DATA||{},tabs=$$(".room-tab"),groups=$$(".room-slider-group");if(!tabs.length||!groups.length)return;const states=new Map;groups.forEach(g=>states.set(g.dataset.room,carousel(g,{slide:".room-slide",dot:".room-dot",prev:".room-prev",next:".room-next"},5000)));const f={title:$("#roomTitle"),subtitle:$("#roomSubtitle"),type:$("#roomType"),people:$("#roomPeople"),lowWeekday:$("#lowWeekday"),lowWeekend:$("#lowWeekend"),highWeekday:$("#highWeekday"),highWeekend:$("#highWeekend")};const activate=k=>{const r=data[k];if(!r)return;tabs.forEach(t=>{const a=t.dataset.room===k;t.classList.toggle("is-active",a);t.setAttribute("aria-selected",a?"true":"false")});groups.forEach(g=>{const a=g.dataset.room===k;g.classList.toggle("is-active",a);const s=states.get(g.dataset.room);a?(s?.show(0),s?.start()):s?.stop()});if(f.title)f.title.textContent=r.title;if(f.subtitle)f.subtitle.textContent=r.subtitle;if(f.type)f.type.textContent=r.title;if(f.people)f.people.textContent=`기준 ${r.base} / 최대 ${r.max}`;if(f.lowWeekday)f.lowWeekday.textContent=`주중 ${r.low_weekday}`;if(f.lowWeekend)f.lowWeekend.textContent=`주말 ${r.low_weekend}`;if(f.highWeekday)f.highWeekday.textContent=`주중 ${r.high_weekday}`;if(f.highWeekend)f.highWeekend.textContent=`주말 ${r.high_weekend}`};tabs.forEach(t=>t.addEventListener("click",()=>activate(t.dataset.room)));activate(tabs.find(t=>t.classList.contains("is-active"))?.dataset.room||"101")}
  function initFacility(){const panels=$$(".facility-panel"),header=$(".facility-header");if(!panels.length||!header)return;let ticking=false;const update=()=>{const marker=scrollY+innerHeight*.58;let current=0;panels.forEach((p,i)=>{if(marker>=p.offsetTop)current=i});panels.forEach((p,i)=>{p.classList.toggle("is-current",i===current);p.classList.toggle("is-passed",i<current)});const overlay=panels[current]?.dataset.header==="overlay";header.classList.toggle("is-overlay",overlay);header.classList.toggle("is-solid",!overlay);ticking=false},request=()=>{if(ticking)return;ticking=true;requestAnimationFrame(update)};addEventListener("scroll",request,{passive:true});addEventListener("resize",request,{passive:true});update()}
  document.addEventListener("DOMContentLoaded",()=>{initMenu();initImageSliders();initReveal();initVideoGuides();initTour();initRooms();initFacility()});
})();
